export const EmojiArray = [
    {
        src:"/emoji/emo_1.png",
        alt:"Emoji"
    },
    {
        src:"/emoji/emo_2.png",
        alt:"Emoji"
    },
    {
        src:"/emoji/emo_3.png",
        alt:"Emoji"
    },
    {
        src:"/emoji/emo_4.png",
        alt:"Emoji"
    },
    {
        src:"/emoji/emo_5.png",
        alt:"Emoji"
    },
    {
        src:"/emoji/emo_6.png",
        alt:"Emoji"
    },
    {
        src:"/emoji/emo_7.png",
        alt:"Emoji"
    },
    {
        src:"/emoji/emo_8.png",
        alt:"Emoji"
    },
    {
        src:"/emoji/emo_9.png",
        alt:"Emoji"
    },
    {
        src:"/emoji/emo_10.png",
        alt:"Emoji"
    },
]